# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 2.1.8
_src_path: gh:algorandfoundation/algokit-fullstack-template
author_email: peter.o@protiusprotocol.com
author_name: Peter
contract_name: hello_world
preset_name: starter
project_name: hello-world

